include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gen.dart"
    - "build/**"

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  errors:
    unused_local_variable: warning
    missing_return: error
    dead_code: info

linter:
  rules:
    always_declare_return_types: true
    always_specify_types: true
    annotate_overrides: true
    avoid_classes_with_only_static_members: true
    avoid_print: true
    avoid_redundant_argument_values: true
    avoid_returning_null_for_future: true
    avoid_returning_null_for_void: true
    avoid_slow_async_io: true
    avoid_types_as_parameter_names: true
    avoid_unnecessary_containers: true
    camel_case_types: true
    constant_identifier_names: true
    curly_braces_in_flow_control_structures: true
    directives_ordering: true
    file_names: true
    library_names: true
    library_prefixes: true
    non_constant_identifier_names: true
    null_check_on_nullable_type_parameter: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_expression_function_bodies: true
    prefer_final_locals: true
    prefer_foreach: true
    prefer_if_null_operators: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_null_aware_operators: true
    prefer_relative_imports: true
    prefer_single_quotes: true
    prefer_typing_uninitialized_variables: true
    require_trailing_commas: true
    sized_box_for_whitespace: true
    slash_for_doc_comments: true
    sort_child_properties_last: true
    sort_pub_dependencies: true
    type_annotate_public_apis: true
    unnecessary_new: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_this: true
    use_function_type_syntax_for_parameters: true
    use_key_in_widget_constructors: true
    use_string_buffers: true
